#!/bin/bash
# nosey installer — interactive bootstrap for fresh systems
#
# Usage:
#   ./scripts/install.sh           # full interactive install
#   ./scripts/install.sh --check   # only verify env, no changes
#   ./scripts/install.sh --no-zeek # skip Zeek install (only DNS-side)
#
# Tested on: Debian 12, Ubuntu 22.04 / 24.04, Raspberry Pi OS Lite 12.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CHECK_ONLY=0
SKIP_ZEEK=0
for arg in "$@"; do
  case "$arg" in
    --check) CHECK_ONLY=1 ;;
    --no-zeek) SKIP_ZEEK=1 ;;
  esac
done

c_red()   { printf "\033[31m%s\033[0m\n" "$*"; }
c_green() { printf "\033[32m%s\033[0m\n" "$*"; }
c_yel()   { printf "\033[33m%s\033[0m\n" "$*"; }
c_blue()  { printf "\033[34m%s\033[0m\n" "$*"; }

require_root() {
  if [[ $EUID -ne 0 ]]; then
    c_red "ERROR: must run as root (sudo $0 ...)"
    exit 2
  fi
}

check_distro() {
  if [[ ! -f /etc/os-release ]]; then
    c_red "ERROR: cannot detect distro"
    exit 2
  fi
  . /etc/os-release
  case "$ID" in
    debian|ubuntu|raspbian) c_green "✓ Detected $PRETTY_NAME";;
    *) c_yel "⚠ untested distro: $PRETTY_NAME (continuing, may need tweaks)";;
  esac
}

apt_install() {
  c_blue "Installing system packages: $*"
  DEBIAN_FRONTEND=noninteractive apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y -qq "$@"
}

install_zeek() {
  if command -v zeek >/dev/null 2>&1; then
    c_green "✓ Zeek already installed"
    return
  fi
  c_blue "Installing Zeek from openSUSE Build Service…"
  if [[ -f /etc/os-release ]]; then
    . /etc/os-release
    case "$ID" in
      debian) repo="Debian_${VERSION_ID}";;
      ubuntu) repo="xUbuntu_${VERSION_ID}";;
      raspbian) repo="Raspbian_${VERSION_ID}";;
      *) c_red "Unknown distro for Zeek repo: $ID"; return 1;;
    esac
  fi
  echo "deb http://download.opensuse.org/repositories/security:/zeek/${repo}/ /" \
    > /etc/apt/sources.list.d/security:zeek.list
  curl -fsSL "https://download.opensuse.org/repositories/security:zeek/${repo}/Release.key" \
    | gpg --dearmor -o /etc/apt/trusted.gpg.d/security_zeek.gpg
  apt-get update -qq
  apt-get install -y zeek
  c_green "✓ Zeek installed at /opt/zeek"
}

# ----- Main -----
c_blue "Nosey installer"
echo

require_root
check_distro

if [[ $CHECK_ONLY -eq 1 ]]; then
  c_blue "Check mode — verifying environment without changes:"
  for pkg in nftables python3 pip nmap git curl; do
    if command -v "$pkg" >/dev/null 2>&1; then c_green "  ✓ $pkg"; else c_red "  ✗ $pkg MISSING"; fi
  done
  command -v zeek >/dev/null 2>&1 && c_green "  ✓ zeek" || c_yel "  ⚠ zeek not installed"
  exit 0
fi

c_blue "1/5  System packages…"
apt_install nftables python3 python3-pip python3-yaml nmap git curl wget

c_blue "2/5  Zeek…"
if [[ $SKIP_ZEEK -eq 0 ]]; then
  install_zeek
else
  c_yel "  → Skipped (--no-zeek)"
fi

c_blue "3/5  Kernel sysctls (IP forwarding)…"
if ! grep -q "^net.ipv4.ip_forward=1" /etc/sysctl.conf; then
  cat >> /etc/sysctl.conf <<'EOF'

# Nosey gateway
net.ipv4.ip_forward=1
net.ipv4.conf.all.rp_filter=2
net.ipv4.conf.all.accept_redirects=0
net.ipv6.conf.all.forwarding=0
EOF
  sysctl -p
  c_green "  ✓ sysctls applied"
else
  c_green "  ✓ already configured"
fi

c_blue "4/5  Nosey config wizard…"
mkdir -p "$REPO_ROOT/config"
[[ -f "$REPO_ROOT/config/nosey.yaml" ]] || cp "$REPO_ROOT/config/nosey.example.yaml" "$REPO_ROOT/config/nosey.yaml"
[[ -f "$REPO_ROOT/config/devices.yaml" ]] || cp "$REPO_ROOT/config/devices.example.yaml" "$REPO_ROOT/config/devices.yaml"

echo
read -rp "Gateway IP (this machine on the LAN, e.g. 192.168.0.210): " GW_IP
read -rp "Pi-hole / AdGuard IP (e.g. 192.168.0.204): " DNS_IP
read -rsp "Pi-hole / AdGuard admin password: " DNS_PASS
echo

sed -i "s|^  ip: 192.168.0.210|  ip: ${GW_IP}|" "$REPO_ROOT/config/nosey.yaml"
sed -i "s|^  dns: 192.168.0.204|  dns: ${DNS_IP}|" "$REPO_ROOT/config/nosey.yaml"
sed -i "s|^  api_url: http://192.168.0.204:8080|  api_url: http://${DNS_IP}:8080|" "$REPO_ROOT/config/nosey.yaml"

cat > /etc/nosey.env <<EOF
PIHOLE_PASSWORD=${DNS_PASS}
EOF
chmod 600 /etc/nosey.env

c_green "  ✓ Config written. Password stored at /etc/nosey.env (600 root:root)."
c_yel  "    To use Nosey: source /etc/nosey.env && bin/nosey ..."

c_blue "5/5  Optional nftables ruleset…"
if [[ ! -f /etc/nftables.conf.bak-pre-nosey ]] && [[ -f /etc/nftables.conf ]]; then
  cp /etc/nftables.conf /etc/nftables.conf.bak-pre-nosey
fi
cat > /etc/nftables.conf <<EOF
#!/usr/sbin/nft -f
# Generated by nosey installer
flush ruleset
table inet filter {
  chain input   { type filter hook input priority filter; policy accept; }
  chain forward {
    type filter hook forward priority filter; policy accept;
    tcp dport 853 counter drop comment "drop DoT"
    udp dport 853 counter drop comment "drop DoQ"
    ip daddr { 1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4, 9.9.9.9, 149.112.112.112 } tcp dport 443 counter drop comment "drop DoH TCP"
    ip daddr { 1.1.1.1, 1.0.0.1, 8.8.8.8, 8.8.4.4, 9.9.9.9, 149.112.112.112 } udp dport 443 counter drop comment "drop DoH QUIC"
  }
  chain output  { type filter hook output priority filter; policy accept; }
}
table ip nat {
  chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;
    ip daddr != ${DNS_IP} udp dport 53 dnat to ${DNS_IP}:53
    ip daddr != ${DNS_IP} tcp dport 53 dnat to ${DNS_IP}:53
  }
  chain postrouting {
    type nat hook postrouting priority srcnat; policy accept;
    oifname "eth0" masquerade
  }
}
table ip6 filter { chain forward { type filter hook forward priority filter; policy drop; } }
EOF

systemctl enable --now nftables
c_green "  ✓ nftables ruleset applied"

echo
c_green "================================================================"
c_green "  Nosey installed."
c_green "================================================================"
echo
echo "Next steps:"
echo "  1. source /etc/nosey.env"
echo "  2. bin/nosey wizard          # interactive device add"
echo "  3. bin/nosey apply"
echo "  4. Follow the per-device playbooks in docs/playbooks/"
echo
echo "Config: $REPO_ROOT/config/nosey.yaml"
echo "Devices: $REPO_ROOT/config/devices.yaml"
echo "Backups of overwritten files (if any) end in .bak-pre-nosey"
